name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set Powershell Bypass (Windows Only)
        if: runner.os == 'Windows'
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      # - name: Display Logs
      #   run: python3 -m exendlr cbs-bot "ready"

      - name: Cleanup Unused Images
        run: docker image prune -f